### ISSUE TITLE
Python3 version?

### ISSUE THREAD

**Issue by Siecje** [jstacoder/graphene-disable-introspection-middleware#1]
On PyPI there is no Python3 version so I can't pip install it in a Python3 environment.

**Comment by jstacoder** [comment]
yea, its not currently published, you can clone the repo and do python3 setup.py install but i guess i could just publish it. ill try today.

**Comment by jstacoder** [comment]
ok, its installable through pip now

**Comment by Siecje** [comment]
@jstacoder Do you get a Internal Server Error when you try to view the introspection with this package? Is that the intended behaviour?

**Comment by jstacoder** [comment]
What’s do you mean “try to view the introspection?” You mean you issued an introspection query?

**Comment by Siecje** [comment]
Yes, this is the query. https://raw.githubusercontent.com/crystallabs/solidus-graphql-schema/master/introspection_query.txt

**Comment by jstacoder** [comment]
the code raises an exception when an introspection query is executed

**Comment by Siecje** [comment]
The response contains `Internal Server Error`. Is this the intended behaviour?

**Comment by jstacoder** [comment]
An error In the context of graphql. Yes, the code raises an exception when an introspection query is made, I guess it could be an option to just return an empty response or something. 
But this was written so one of my graphql api’s wouldn’t accept introspection queries, because if your hitting that endpoint you don’t need to know more about it, so it wasn’t much concern of mine what was returned, as long as it wasn’t the actual result. But if it would be helpful for you I could add the option to not throw an exception

**Comment by Siecje** [comment]
This is the response
```
{
  "errors": [
    {
      "type": "IntrospectionDisabledException",
      "message": "Internal server error",
      "code": "error",
      "path": [
        "__schema"
      ],
      "operation": "query"
    }
  ],
  "data": null
}
```

**Comment by jstacoder** [comment]
yes, when a graphql query raises an exception, it is returned under the errors key in the response, if the response does not have an errors key it means it should return everything you asked for, and since i am limiting the response, i am raising an exception to the user(as you see it is of type `IntrospectionDisabledException`), and i know that an error being returned would tell someone that obviously this query is being squelched, but so would a response with no error and empty data, but that would violate graphql which says: if a query does not error, it should succeed
